// src/pages/ReportNews.vue
<template>
  <div class="container">
    <h2>{{ t('nav_report') }}</h2>
    <form class="form" @submit.prevent="submit">
      <div class="form-row">
        <label>{{ t('reportTitle') }}</label>
        <input v-model="title" type="text" />
      </div>
      <div class="form-row">
        <label>{{ t('reportSummary') }}</label>
        <textarea v-model="summary" rows="3"></textarea>
      </div>
      <div class="form-row">
        <label>{{ t('reportContent') }}</label>
        <textarea v-model="content" rows="6"></textarea>
      </div>
      <div class="form-row">
        <label>{{ t('reportReporter') }}</label>
        <input v-model="reporter" type="text" />
      </div>
      <div class="form-row">
        <label>{{ t('reportImageUrl') }}</label>
        <input v-model="imageUrl" type="text" />
      </div>
      <div style="display:flex; gap:8px">
        <button class="btn" type="submit">{{ t('reportSubmit') }}</button>
        <RouterLink class="btn" to="/">{{ t('backHome') }}</RouterLink>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { useStore } from '../store'
import { useI18n } from '../i18n'

const router = useRouter()
const { addNews } = useStore()
const { t } = useI18n()

const title = ref('')
const summary = ref('')
const content = ref('')
const reporter = ref('')
const imageUrl = ref('')

const submit = () => {
  if (!title.value.trim() || !summary.value.trim() || !content.value.trim() || !reporter.value.trim()) {
    alert(t('reportValidationAlert'))
    return
  }
  addNews({ title: title.value.trim(), summary: summary.value.trim(), content: content.value.trim(), reporter: reporter.value.trim(), imageUrl: imageUrl.value.trim() || undefined })
  router.push('/')
}
</script>

<style scoped>
.btn { border: 1px solid var(--border); padding:6px 10px; background:#fff; cursor:pointer }
.form { display:grid; gap:12px }
.form-row { display:grid; gap:6px }
.form-row input, .form-row textarea { padding:8px; border:1px solid var(--border); border-radius:4px }
</style>

// src/pages/ReportNews.tsx
import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useStore } from "../store";
import { useI18n } from "../i18n";

export default function ReportNewsPage() {
  const nav = useNavigate();
  const { addNews } = useStore();
  const { t } = useI18n();
  const [title, setTitle] = useState("");
  const [summary, setSummary] = useState("");
  const [content, setContent] = useState("");
  const [reporter, setReporter] = useState("");
  const [imageUrl, setImageUrl] = useState("");

  const submit = (e: FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !summary.trim() || !content.trim() || !reporter.trim()) {
      alert(t('reportValidationAlert'));
      return;
    }
    addNews({ title: title.trim(), summary: summary.trim(), content: content.trim(), reporter: reporter.trim(), imageUrl: imageUrl.trim() || undefined });
    nav("/");
  };

  return (
    <div className="container">
      <h2>{t('reportPageTitle')}</h2>
      <form className="form" onSubmit={submit}>
        <div className="form-row">
          <label>{t('titleLabel')}</label>
          <input value={title} onChange={(e)=>setTitle(e.target.value)} />
        </div>
        <div className="form-row">
          <label>{t('summaryLabel')}</label>
          <textarea rows={3} value={summary} onChange={(e)=>setSummary(e.target.value)} />
        </div>
        <div className="form-row">
          <label>{t('contentLabel')}</label>
          <textarea rows={6} value={content} onChange={(e)=>setContent(e.target.value)} />
        </div>
        <div className="form-row">
          <label>{t('reporterLabel')}</label>
          <input value={reporter} onChange={(e)=>setReporter(e.target.value)} />
        </div>
        <div className="form-row">
          <label>{t('imageUrlLabel')}</label>
          <input value={imageUrl} onChange={(e)=>setImageUrl(e.target.value)} placeholder="https://..." />
        </div>
        <div className="actions">
          <button type="submit" className="btn primary">{t('submitReport')}</button>
          <Link to="/" className="btn">{t('returnHome')}</Link>
        </div>
      </form>
    </div>
  );
}
