// src/App.tsx
import './App.css'
import { Link, NavLink, Route, Routes } from 'react-router-dom'
import { useI18n } from './i18n'
import HomePage from './pages/Home'
import NewsDetailPage from './pages/NewsDetail'
import VotePage from './pages/Vote'
import ReportNewsPage from './pages/ReportNews'
import ImportRSSPage from './pages/ImportRSS'

function App() {
  const { t, lang, setLang } = useI18n();
  return (
    <div className="layout">
      <header className="header">
        <div className="brand">
          <Link to="/">{t('brand')}</Link>
        </div>
        <nav className="nav" style={{display:'flex', alignItems:'center'}}>
          <span style={{color:'#666'}}>{t('language')}</span>
          <select value={lang} onChange={(e)=>setLang(e.target.value as any)} style={{marginLeft:8}}>
            <option value="zh">{t('zh')}</option>
            <option value="en">{t('en')}</option>
          </select>
          <span style={{marginLeft:12}}></span>
          <NavLink to="/" end className={({isActive}) => isActive ? 'active' : ''}>{t('nav_home')}</NavLink>
          <NavLink to="/report" className={({isActive}) => isActive ? 'active' : ''}>{t('nav_report')}</NavLink>
          <NavLink to="/import" className={({isActive}) => isActive ? 'active' : ''}>{t('nav_import')}</NavLink>
        </nav>
      </header>
      <main className="main">
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/news/:id" element={<NewsDetailPage />} />
          <Route path="/news/:id/vote" element={<VotePage />} />
          <Route path="/report" element={<ReportNewsPage />} />
          <Route path="/import" element={<ImportRSSPage />} />
        </Routes>
      </main>
      <footer className="footer">© {new Date().getFullYear()} {t('brand')} Demo</footer>
    </div>
  )
}

export default App

// src/App.vue
<template>
  <div class="layout">
    <div v-show="state.progressActive" class="top-progress"><div class="bar" :style="{ width: state.progressValue + '%' }"></div></div>
    <header class="header">
      <div class="brand">
        <RouterLink to="/">{{ t('brand') }}</RouterLink>
      </div>
      <nav class="nav" style="display:flex; align-items:center">
        <span style="color:#666">{{ t('language') }}</span>
        <select :value="lang" @change="onLangChange" style="margin-left:8px">
          <option value="zh">{{ t('zh') }}</option>
          <option value="en">{{ t('en') }}</option>
        </select>
        <span style="margin-left:12px"></span>
        <RouterLink to="/" active-class="active" exact>{{ t('nav_home') }}</RouterLink>
        <RouterLink to="/report" active-class="active">{{ t('nav_report') }}</RouterLink>
        <RouterLink to="/import" active-class="active">{{ t('nav_import') }}</RouterLink>
      </nav>
    </header>
    <main class="main">
      <RouterView />
    </main>
    <footer class="footer">© {{ new Date().getFullYear() }} {{ t('brand') }} Demo</footer>
  </div>
  
</template>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import { useI18n } from './i18n'
import { useStore } from './store'

const { t, lang, setLang } = useI18n()
const { state } = useStore()
const onLangChange = (e: Event) => {
  const target = e.target as HTMLSelectElement
  setLang(target.value as any)
}
</script>

<style>
/* styles are imported via main.ts (App.css, index.css) */
.top-progress { position: fixed; top: 0; left: 0; width: 100%; height: 3px; background: transparent; z-index: 9999 }
.top-progress .bar { height: 100%; background: linear-gradient(90deg, #4f46e5, #06b6d4); transition: width .2s ease }
</style>
